// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6YkJGIFIWDL4tUUwG5FPjcS9KyefWW6Q',
    appId: '1:75779513410:web:edd85327af5b86f8afe1db',
    messagingSenderId: '75779513410',
    projectId: 'kigali-city-services-caa28',
    authDomain: 'kigali-city-services-caa28.firebaseapp.com',
    storageBucket: 'kigali-city-services-caa28.firebasestorage.app',
    measurementId: 'G-51WL2MV8Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxuTMoyhMlrkqCISqhhIiMmWiFhUdhSv0',
    appId: '1:75779513410:android:b043bb5bfae9e1b7afe1db',
    messagingSenderId: '75779513410',
    projectId: 'kigali-city-services-caa28',
    storageBucket: 'kigali-city-services-caa28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsriVC4DGWSIccsQ-owdXehLkCx9heXA',
    appId: '1:75779513410:ios:c3cfbae862ce8600afe1db',
    messagingSenderId: '75779513410',
    projectId: 'kigali-city-services-caa28',
    storageBucket: 'kigali-city-services-caa28.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsriVC4DGWSIccsQ-owdXehLkCx9heXA',
    appId: '1:75779513410:ios:c3cfbae862ce8600afe1db',
    messagingSenderId: '75779513410',
    projectId: 'kigali-city-services-caa28',
    storageBucket: 'kigali-city-services-caa28.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6YkJGIFIWDL4tUUwG5FPjcS9KyefWW6Q',
    appId: '1:75779513410:web:42ba78b5c832c882afe1db',
    messagingSenderId: '75779513410',
    projectId: 'kigali-city-services-caa28',
    authDomain: 'kigali-city-services-caa28.firebaseapp.com',
    storageBucket: 'kigali-city-services-caa28.firebasestorage.app',
    measurementId: 'G-3HF95M24YS',
  );
}
